language: php
php:
- 5.5

branches:
  only:
    - master
    - phpu-sample

before_script:
- composer install
- sh start-sele.sh
- bin/behat --init
- printenv TRAVIS_BUILD_ID
- printenv TRAVIS_BUILD_NUMBER
- printenv TRAVIS_JOB_ID
- printenv TRAVIS_JOB_NUMBER

script:
- bin/phpunit -c phpunit-conf
- bin/behat -p firefox